### ISSUE TITLE
how to test？

### ISSUE THREAD

**Issue by watertianyi** [SHI-Labs/SH-GAN#1]

**Comment by xingqian2018** [comment]
Please check the evaluation session provided in README.md. Let me if you have further issues.

**Comment by Hydrageno** [comment]
> Please check the evaluation session provided in README.md. Let me if you have further issues.

Hello! how can I test my own picture?

**Comment by fabricecarles** [comment]
but evaluation session provided in README.md does not provide image inpainting result (for visual inspection).
Please, could you explain how to make inference and mask preparation ?
